ALTER TABLE creator_profiles ADD COLUMN IF NOT EXISTS show_age BOOLEAN DEFAULT TRUE;
ALTER TABLE creator_profiles ADD COLUMN IF NOT EXISTS show_location BOOLEAN DEFAULT TRUE;
ALTER TABLE creator_profiles ADD COLUMN IF NOT EXISTS show_languages BOOLEAN DEFAULT TRUE;
ALTER TABLE creator_profiles ADD COLUMN IF NOT EXISTS show_body_type BOOLEAN DEFAULT TRUE;
ALTER TABLE creator_profiles ADD COLUMN IF NOT EXISTS show_ethnicity BOOLEAN DEFAULT TRUE;
ALTER TABLE creator_profiles ADD COLUMN IF NOT EXISTS show_height_weight BOOLEAN DEFAULT TRUE;
