ALTER TABLE streams ADD COLUMN IF NOT EXISTS is_paid BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE streams ADD COLUMN IF NOT EXISTS admission_price NUMERIC(10,2) NOT NULL DEFAULT 0.00;
ALTER TABLE streams ADD COLUMN IF NOT EXISTS chat_enabled BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE streams ADD COLUMN IF NOT EXISTS slow_mode BOOLEAN NOT NULL DEFAULT FALSE;
ALTER TABLE streams ADD COLUMN IF NOT EXISTS slow_mode_interval INTEGER;
ALTER TABLE streams ADD COLUMN IF NOT EXISTS max_viewers INTEGER;
ALTER TABLE streams ADD COLUMN IF NOT EXISTS stream_category VARCHAR(255);
ALTER TABLE streams ADD COLUMN IF NOT EXISTS thumbnail_url VARCHAR(255);
