ALTER TABLE chat_rooms_v2
    ADD COLUMN IF NOT EXISTS chat_mode VARCHAR(50) NOT NULL DEFAULT 'PUBLIC',
    ADD COLUMN IF NOT EXISTS is_private BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS is_paid BOOLEAN NOT NULL DEFAULT FALSE,
    ADD COLUMN IF NOT EXISTS price_per_message BIGINT NULL,
    ADD COLUMN IF NOT EXISTS name VARCHAR(255) NULL;
