package com.joinlivora.backend.analytics;

public enum AnalyticsEventType {
    VISIT,
    USER_REGISTERED,
    USER_LOGIN_SUCCESS,
    USER_LOGIN_FAILED,
    SUBSCRIPTION_STARTED,
    SUBSCRIPTION_CANCELED,
    PAYMENT_SUCCEEDED,
    PAYMENT_FAILED,
    EXPERIMENT_ASSIGNED,
    PPV_CHAT_ACCESS_GRANTED,
    PPV_CHAT_MESSAGE_BLOCKED,
    SUPERTIP_SENT,
    SLOW_MODE_BYPASS_GRANTED,
    SLOW_MODE_BYPASS_EXPIRED,
    SLOW_MODE_BYPASS_REVOKED,
    HIGHLIGHTED_MESSAGE_SENT,
    HIGHLIGHTED_MESSAGE_REFUNDED,
    CHAT_MODE_CHANGED,
    STREAM_JOIN,
    STREAM_LEAVE,
    CHAT_MESSAGE_SENT
}
