package com.joinlivora.backend.fraud.model;

public enum FraudSignalType {
    NEW_DEVICE,
    NEW_IP,
    VPN_PROXY,
    TOR_EXIT,
    DEVICE_MISMATCH,
    VELOCITY_WARNING,
    CHAT_SPAM,
    PAYMENT_FAILURE,
    CHARGEBACK,
    COUNTRY_MISMATCH,
    IP_MISMATCH,
    AUTOMATIC_ESCALATION,
    FRAUD_COOLDOWN,
    ADMIN_OVERRIDE,
    ADMIN_UNBLOCK,
    TRUST_EVALUATION_BLOCK,
    CHARGEBACK_CORRELATION,
    AML_HIGH_RISK,
    COLLUSION_DETECTED,
    SUSPICIOUS_TIP_PATTERN,
    NEW_ACCOUNT_TIPPING,
    NEW_ACCOUNT_TIPPING_HIGH,
    NEW_ACCOUNT_TIPPING_MEDIUM,
    NEW_ACCOUNT_TIP_CLUSTER,
    RAPID_TIP_REPEATS
}
